eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
        instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
        lease:
            duration: 5
    instance:
        leaseRenewalIntervalInSeconds: 5 # intervalSeconds between subsequent heartbeats sent to Eureka server
        leaseExpirationDurationInSeconds: 2 # time that Eureka server waits since it received last heartbeat before it can evict this instance

management:
  endpoints:
    web:
        exposure:
            include: ["health", "info", "refresh"]
  security:
    enabled: false

server:
    port: ${API_GATEWAY_PORT:9094}

zuul:
#    sensitiveHeaders: Cookie,Set-Cookie
    routes:
        product:
            path: /products/**
            serviceId: product-service
        user:
            path: /users/**
            serviceId: user-service

#security:
#    oauth2:
#        resource:
#            jwt:
#                key-value: 123