eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 9094

spring:
    application:
        name: API-Gateway

zuul:
#    sensitiveHeaders: Cookie,Set-Cookie
    routes:
        product:
            path: /products/**
            serviceId: product-service
        user:
            path: /users/**
            serviceId: user-service

#security:
#    oauth2:
#        resource:
#            jwt:
#                key-value: 123