eureka:
    instance:
            leaseRenewalIntervalInSeconds: 5
            leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        healthcheck:
            enabled: true
        lease:
              duration: 5
management:
  security:
    enabled: false
  endpoints:
    web:
        exposure:
            include : "*"

server:
    port: 9093
spring:
    application:
        name: product-service

    datasource:
        url: jdbc:hsqldb:mem:products
        username: sa
        password: 1
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.HSQLDialect
        show-sql: true
