eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 9093
spring:
    application:
        name: product-service

    datasource:
        url: jdbc:hsqldb:mem:products
        username: sa
        password: 1
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.HSQLDialect
        show-sql: true
