eureka:
    instance:
            leaseRenewalIntervalInSeconds: 5
            leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
        healthcheck:
            enabled: true
        lease:
              duration: 5
server:
    port: ${PRODUCT_SERVICE_PORT:9093}
spring:
    datasource:
        url: jdbc:hsqldb:mem:products
        username: sa
        password: 1
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.HSQLDialect
        show-sql: true
