eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
        instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
        lease:
            duration: 5
    instance:
        leaseRenewalIntervalInSeconds: 5 # intervalSeconds between subsequent heartbeats sent to Eureka server
        leaseExpirationDurationInSeconds: 2 # time that Eureka server waits since it received last heartbeat before it can evict this instance

management:
  security:
    enabled: false
  endpoints:
    web:
        exposure:
            include: ["health", "info", "refresh"]
# custom attribute for the actuator info endpoint
info:
  app:
    name: product-service


server:
    port: ${PRODUCT_SERVICE_PORT:9093}
spring:
    datasource:
        url: jdbc:hsqldb:mem:products
        username: sa
        password: 1
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.HSQLDialect
        show-sql: true
