spring:
    datasource:
        url: jdbc:hsqldb:mem:products
        username: sa
        password: 1
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.HSQLDialect
        show-sql: true
