drop table product if exists;

create table product (productId bigint generated by default as identity (start with 1) PRIMARY KEY, pname varchar(50),
                        productType varchar(10) not null, productPrice decimal(8,2));
                        
