eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
server:
    port: ${PORT:8761}

management:
  security:
    enabled: false
  endpoints:
    web:
        exposure:
            include : "*"
info:
  app:
    name: discovery-service
