spring:
    application:
        name: discovery-service

server:
    port: ${DISCOVERY_PORT:8761}

eureka:
    instance:
        hostname: ${EUREKA_HOSTNAME:localhost}
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
        exposure:
            include: ["health", "info", "refresh"]
info: #InfoContributor
  app:
    name: discovery-service
