eureka:
    instance:
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 2

    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
        healthcheck:
            enabled: true
        lease:
              duration: 5
info:
  app:
    name: config-service

management:
  security:
    enabled: false
  endpoints:
    web:
        exposure:
            include : "*"
spring:
    application:
        name: Spring-Config
    cloud:
      config:
        server:
            git:
                uri: D:\\Workspace\\config-server-repo
            cloneOnStart: true
server:
  port: ${PORT:9999}
