spring:
    cloud:
      config:
        server:
            git:
#                uri: D:/Workspace/config-server-repo
                uri: https://github.com/MohammadRasool-Shaik/config-server-repo.git
                cloneOnStart: true
#               searchPaths: #If we have to specify a particular folder we can provide the location via searchPaths.
                search-paths: '{application}'

eureka:
    client:
        enabled: true
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
        healthcheck:
            enabled: true
        registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
        instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
        lease:
            duration: 5
    instance:
        leaseRenewalIntervalInSeconds: 5 # intervalSeconds between subsequent heartbeats sent to Eureka server
        leaseExpirationDurationInSeconds: 2 # time that Eureka server waits since it received last heartbeat before it can evict this instance

# Server properties
server:
  port: 9999
