eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

spring:
    application:
        name: Spring-Config
    cloud:
      config:
        server:
server:
  port: 9999
